version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - service-registry/target/service-registry-0.0.1-SNAPSHOT.jar
    - api-gateway/target/api-gateway-0.0.1-SNAPSHOT.jar
    - portal-service/target/portal-service-0.0.1-SNAPSHOT.jar
    - listing-service/target/listing-service-0.0.1-SNAPSHOT.jar
    - user-service/target/user-service-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes