server:
  port: 9191
 
spring: 
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**    
        - id: LISTING-SERVICE
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/listings/**
        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comments/**
        - id: PORTAL-SERVICE
          uri: lb://PORTAL-SERVICE
          predicates:
            - Path=/**   
        - id: WEB-SERVICE
          uri: lb://WEB-SERVICE
          predicates:
            - Path=/**     
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
      hostname: localhost