server:
  port: 9191
 
spring: 
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: LISTING-SERVICE
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/listings/**
        
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
      hostname: localhost